### ISSUE TITLE
installing via Alcatraz fails

### ISSUE THREAD

**Issue by i-n-g-o** [openframeworks/OFXcodeMenu#40]
It failed when installing via alcatraz on:
OSX: 10.10.5
XCode: 6.4
XCode: 7.0

It seems to start downloading, but fails after a short while.

**Comment by admsyn** [comment]
Does Alcatraz work on Xcode 7.0 for you @i-n-g-o ? It looks like [it's an open issue](https://github.com/supermarin/Alcatraz/issues/352).

It may be getting confused due to the URL change from admsyn/OFPlugin to openFrameworks/OFXcodeMenu . I'll see about updating it once I can get Alctraz on Xcode 7 :)

**Comment by i-n-g-o** [comment]
alcatraz seems to work fine. just installed some eyecandy :)

**Comment by bakercp** [comment]
I'm getting the same issue, btw.

**Comment by admsyn** [comment]
It's been merged into Alcatraz, can someone confirm if the install works now?

**Comment by bakercp** [comment]
Fixed by https://github.com/supermarin/alcatraz-packages/pull/378#event-418341423

**Comment by bakercp** [comment]
I had to press install twice for some reason, but it eventually worked.

**Comment by i-n-g-o** [comment]
aha name changed to `OFXcodeMenu`
works with pressing install once. :)
