### ISSUE TITLE
Do you have any plan to deal with Xcode 8 ?

### ISSUE THREAD

**Issue by kidapu** [openframeworks/OFXcodeMenu#46]
I have tried to install OFXcodeMenu in Xcode 8 , but I can't .

Do you have any plan to support for Xcode 8 ?

**Comment by thomasvanta** [comment]
Looks like plugins are not supported by Xcode 8+ anymore.
There will be an extensions style option in the future, but not ready yet.
Take a look here: https://github.com/alcatraz/Alcatraz/issues/475

**Comment by kidapu** [comment]
@thomasvanta 
Thank you for your reply. 
I decided to use Xcode 7.3 until extensions style option arrive!

**Comment by faaip** [comment]
Stuck at Xcode 8, but I'd really love to keep using OFXCodeMenu. Does anyone know if it's possible or doable to port to xcode 8? Love to give it a shot.

**Comment by admsyn** [comment]
I don't think it's possible, this issue on Alcatraz has more information https://github.com/alcatraz/Alcatraz/issues/475

To the best of my knowledge, Xcode 8+ only supports "Source Editor" plugins, which only have access to the text-editing portion of Xcode.

If someone knows of a way to continue manipulating project files via Xcode plugin feel free to get in touch with me and maybe we can figure something out. Otherwise I think the only way to get this functionality would be with an external tool like cocoapods/carthage
